#!/bin/sh
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
SOURCE="$ROOT/source/surge"
REGION_FILE="$ROOT/source/regions.json"

REGION_HONG_KONG=$(jq -er '.hongKong' "$REGION_FILE")
REGION_JAPAN=$(jq -er '.japan' "$REGION_FILE")
REGION_SINGAPORE=$(jq -er '.singapore' "$REGION_FILE")
REGION_UNITED_STATES=$(jq -er '.unitedStates' "$REGION_FILE")
REGION_UNITED_KINGDOM=$(jq -er '.unitedKingdom' "$REGION_FILE")
REGION_TAIWAN=$(jq -er '.taiwan' "$REGION_FILE")

render_template() {
  sub_store_target=$2
  awk \
    -v sub_store_target="$sub_store_target" \
    -v region_hong_kong="$REGION_HONG_KONG" \
    -v region_japan="$REGION_JAPAN" \
    -v region_singapore="$REGION_SINGAPORE" \
    -v region_united_states="$REGION_UNITED_STATES" \
    -v region_united_kingdom="$REGION_UNITED_KINGDOM" \
    -v region_taiwan="$REGION_TAIWAN" '
      {
        gsub(/\{\{SUB_STORE_TARGET\}\}/, sub_store_target)
        gsub(/\{\{REGION_HONG_KONG\}\}/, region_hong_kong)
        gsub(/\{\{REGION_JAPAN\}\}/, region_japan)
        gsub(/\{\{REGION_SINGAPORE\}\}/, region_singapore)
        gsub(/\{\{REGION_UNITED_STATES\}\}/, region_united_states)
        gsub(/\{\{REGION_UNITED_KINGDOM\}\}/, region_united_kingdom)
        gsub(/\{\{REGION_TAIWAN\}\}/, region_taiwan)
        print
      }
    ' "$1"
}

build_profile() {
  general_source=$1
  target_relative_path=$2
  routing_source=$3
  sub_store_target=$4
  title=$5
  target="$ROOT/Surge/$target_relative_path"
  temporary="$target.tmp"

  mkdir -p "$(dirname "$target")"

  {
    printf '%s\n' "# Generated from source/surge. Do not edit this file in the repository."
    printf '%s\n' "# $title"
    printf '%s\n' '# Keep device-specific nodes and subscription URLs in the imported local copy.'
    printf '\n'
    render_template "$SOURCE/$general_source" "$sub_store_target"
    printf '\n'
    render_template "$SOURCE/$routing_source" "$sub_store_target"
  } > "$temporary"

  mv "$temporary" "$target"
}

build_profile macos5.general.conf macOS/Surge-5.conf macos5.routing.conf SurgeMac 'Surge Mac 5.7+ base profile'
build_profile macos.general.conf macOS/Surge-6.conf routing.conf SurgeMac 'Surge Mac 6.0+ base profile'
build_profile ios.general.conf iOS/Surge-6.conf routing.conf Surge 'Surge iOS and iPadOS base profile'

build_copy() {
  source=$1
  target=$2
  temporary="$target.tmp"
  mkdir -p "$(dirname "$target")"
  render_template "$source" '' > "$temporary"
  mv "$temporary" "$target"
}

build_copy "$ROOT/source/quantumultx/qlingxing.conf" "$ROOT/QuantumultX/qlingxing.conf"
build_copy "$ROOT/source/loon/Loon.conf" "$ROOT/Loon/Loon.conf"
