#!/bin/sh
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
SOURCE="$ROOT/source/surge"
VERSION_FILE="$ROOT/source/versions.json"
REGION_FILE="$ROOT/source/regions.json"

SUB_STORE_VERSION=$(jq -er '.subStore' "$VERSION_FILE")
REGION_HONG_KONG=$(jq -er '.hongKong' "$REGION_FILE")
REGION_JAPAN=$(jq -er '.japan' "$REGION_FILE")
REGION_SINGAPORE=$(jq -er '.singapore' "$REGION_FILE")
REGION_UNITED_STATES=$(jq -er '.unitedStates' "$REGION_FILE")
REGION_UNITED_KINGDOM=$(jq -er '.unitedKingdom' "$REGION_FILE")
REGION_TAIWAN=$(jq -er '.taiwan' "$REGION_FILE")

render_template() {
  awk \
    -v sub_store_version="$SUB_STORE_VERSION" \
    -v region_hong_kong="$REGION_HONG_KONG" \
    -v region_japan="$REGION_JAPAN" \
    -v region_singapore="$REGION_SINGAPORE" \
    -v region_united_states="$REGION_UNITED_STATES" \
    -v region_united_kingdom="$REGION_UNITED_KINGDOM" \
    -v region_taiwan="$REGION_TAIWAN" '
      {
        gsub(/\{\{SUB_STORE_VERSION\}\}/, sub_store_version)
        gsub(/\{\{REGION_HONG_KONG\}\}/, region_hong_kong)
        gsub(/\{\{REGION_JAPAN\}\}/, region_japan)
        gsub(/\{\{REGION_SINGAPORE\}\}/, region_singapore)
        gsub(/\{\{REGION_UNITED_STATES\}\}/, region_united_states)
        gsub(/\{\{REGION_UNITED_KINGDOM\}\}/, region_united_kingdom)
        gsub(/\{\{REGION_TAIWAN\}\}/, region_taiwan)
        print
      }
    ' "$1"
}

build_profile() {
  platform=$1
  title=$2
  target="$ROOT/Surge/$platform/Surge-6.conf"
  temporary="$target.tmp"

  mkdir -p "$(dirname "$target")"

  {
    printf '%s\n' "# Generated from source/surge. Do not edit this file in the repository."
    printf '%s\n' "# $title"
    printf '%s\n' '# Keep device-specific nodes and subscription URLs in the imported local copy.'
    printf '\n'
    render_template "$SOURCE/$platform.general.conf"
    printf '\n'
    render_template "$SOURCE/routing.conf"
  } > "$temporary"

  mv "$temporary" "$target"
}

build_profile macOS 'Surge Mac 6.0+ base profile'
build_profile iOS 'Surge iOS and iPadOS base profile'

build_copy() {
  source=$1
  target=$2
  temporary="$target.tmp"
  mkdir -p "$(dirname "$target")"
  render_template "$source" > "$temporary"
  mv "$temporary" "$target"
}

build_copy "$ROOT/source/quantumultx/qlingxing.conf" "$ROOT/QuantumultX/qlingxing.conf"
build_copy "$ROOT/source/quantumultx/Sub-Store.conf" "$ROOT/QuantumultX/Modules/Sub-Store.conf"
build_copy "$ROOT/source/loon/Loon.conf" "$ROOT/Loon/Loon.conf"
build_copy "$ROOT/source/loon/Sub-Store.plugin" "$ROOT/Loon/Plugins/Sub-Store.plugin"
build_copy "$ROOT/source/loon/Sub-Store-Parser.plugin" "$ROOT/Loon/Plugins/Sub-Store-Parser.plugin"
build_copy "$ROOT/source/loon/Spotify-Enhance.plugin" "$ROOT/Loon/Plugins/Spotify-Enhance.plugin"
build_copy "$ROOT/source/loon/YouTube-AdBlock.plugin" "$ROOT/Loon/Plugins/YouTube-AdBlock.plugin"
build_copy "$ROOT/source/loon/BiliBili-Enhance.plugin" "$ROOT/Loon/Plugins/BiliBili-Enhance.plugin"
build_copy "$ROOT/source/loon/Emby-Public-Experimental.plugin" "$ROOT/Loon/Plugins/Emby-Public-Experimental.plugin"
build_copy "$ROOT/source/surge/Sub-Store.sgmodule" "$ROOT/Surge/Module/Surge.sgmodule"
build_copy "$ROOT/source/surge/Spotify.module" "$ROOT/Surge/Module/spotify.module"
build_copy "$ROOT/source/surge/BiliBili-AdBlock.sgmodule" "$ROOT/Surge/Modules/BiliBili-AdBlock.sgmodule"
build_copy "$ROOT/source/surge/Emby-Public-Experimental.sgmodule" "$ROOT/Surge/Modules/Emby-Public-Experimental.sgmodule"
