[General]
loglevel = notify
show-error-page-for-reject = true
all-hybrid = false
ipv6 = false
test-timeout = 5
internet-test-url = https://connect.rom.miui.com/generate_204
proxy-test-url = https://www.gstatic.com/generate_204
dns-server = 223.5.5.5, 119.29.29.29
encrypted-dns-server = https://dns.alidns.com/dns-query, https://doh.pub/dns-query
exclude-simple-hostnames = true
read-etc-hosts = true
http-api-web-dashboard = true
skip-proxy = 127.0.0.1, localhost, *.local, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
always-real-ip = *.srv.nintendo.net, *.stun.playstation.net, xbox.*.microsoft.com, *.xboxlive.com, *.battlenet.com.cn, *.battlenet.com, *.blzstatic.cn, *.battle.net
